#!/usr/bin/env python3
"""Type-checks every Objective-C code block in the consumer documents.

Each ```objc block is compiled with `clang -fsyntax-only` against the core's public headers and the
Objective-C headers Swift generates for the three companions. A snippet that names a class, selector,
or constant the packages do not declare fails here, at the Markdown line that names it.

A snippet is a fragment: it uses variables the surrounding prose supplies (`error`, `cgImage`,
`releaseDirectory`). `snippet-context.h` beside this script declares those names once, with the types
the documents give them. The checker places a block's statements in a function body after that
context, hoists `@import` / `#import` lines to file scope, and moves `@interface` / `@implementation`
/ `@protocol` sections to file scope ahead of the function.

An HTML comment on the lines directly above a fence adjusts that one block:

    <!-- objc-check: skip (reason) -->        the block is not compiled; the reason is required
    <!-- objc-check: given NSURL *songURL; --> extra declarations, placed after the shared context
    <!-- objc-check: continues -->             the block compiles in the scope of the block before it

The companion headers are generated by each package's build. The checker runs `swift build --target
<package>` for each companion first (a second or two when nothing changed), so a header never lags the
Swift source; `--no-build` uses whatever headers `.build` already holds.

    Tools/doc-snippets/check-objc.py                 # README.md, Docs/examples.md, Docs/inference-guide.md
    Tools/doc-snippets/check-objc.py Docs/examples.md
    Tools/doc-snippets/check-objc.py --no-build      # skip the companion builds
    Tools/doc-snippets/check-objc.py --keep DIR      # keep the generated sources in DIR
"""

import argparse
import concurrent.futures
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTEXT = Path(__file__).resolve().parent / "snippet-context.h"
DEFAULT_DOCUMENTS = ["README.md", "Docs/examples.md", "Docs/inference-guide.md"]
COMPANIONS = ["InferKitMLX", "InferKitFoundationModels", "InferKitAppleSwift"]
DEPLOYMENT_TARGET = "arm64-apple-macos26.0"

# Unused locals and property reads are how a fragment shows a value; everything else is an error.
SUPPRESSED_WARNINGS = [
    "-Wno-unused-variable",
    "-Wno-unused-but-set-variable",
    "-Wno-unused-value",
    "-Wno-unused-getter-return-value",
    "-Wno-unused-function",
]

DIRECTIVE = re.compile(r"^\s*<!--\s*objc-check:\s*(skip|given|continues)\b(.*?)-->\s*$")
FILE_SCOPE_OPEN = re.compile(r"^\s*@(interface|implementation|protocol)\b")
FILE_SCOPE_CLOSE = re.compile(r"^\s*@end\b")
HOISTED = re.compile(r"^\s*(@import|#import|#include)\b")


class Block:
    def __init__(self, document, first_line, lines, directives):
        self.document = document
        self.first_line = first_line
        self.lines = lines
        self.skip_reason = None
        self.givens = []
        self.continues = False
        for kind, argument in directives:
            if kind == "skip":
                self.skip_reason = argument.strip() or "(no reason given)"
            elif kind == "given":
                self.givens.append(argument.strip())
            else:
                self.continues = True

    @property
    def location(self):
        return f"{self.document}:{self.first_line}"


def read_blocks(document):
    lines = (ROOT / document).read_text().split("\n")
    blocks = []
    index = 0
    while index < len(lines):
        if lines[index].strip() != "```objc":
            index += 1
            continue
        directives = []
        above = index - 1
        while above >= 0 and DIRECTIVE.match(lines[above]):
            match = DIRECTIVE.match(lines[above])
            directives.insert(0, (match.group(1), match.group(2)))
            above -= 1
        end = index + 1
        while end < len(lines) and not lines[end].startswith("```"):
            end += 1
        blocks.append(Block(document, index + 2, lines[index + 1:end], directives))
        index = end + 1
    return blocks


def line_marker(line_number, document):
    return f'#line {line_number} "{ROOT / document}"'


def split_block(block):
    """Returns (hoisted, file_scope, body) as lists of source lines carrying #line markers."""
    hoisted, file_scope, body = [], [], []
    section = body
    previous = None
    for offset, text in enumerate(block.lines):
        if section is body and FILE_SCOPE_OPEN.match(text):
            section = file_scope
        destination = hoisted if HOISTED.match(text) else section
        if destination is not previous:
            destination.append(line_marker(block.first_line + offset, block.document))
        destination.append(text)
        previous = destination
        if section is file_scope and FILE_SCOPE_CLOSE.match(text):
            section = body
    return hoisted, file_scope, body


def translation_unit(chain, context):
    """Builds one source file from a block and the blocks it continues, outermost first."""
    imports = ["@import Foundation;", "@import CoreGraphics;", "@import Metal;", "@import AVFoundation;",
               "@import CoreML;", "@import InferKit;"] + [f"@import {name};" for name in COMPANIONS]
    hoisted_all, file_scope_all, bodies = [], [], []
    for block in chain:
        hoisted, file_scope, body = split_block(block)
        hoisted_all += hoisted
        file_scope_all += file_scope
        givens = [line_marker(block.first_line - 1, block.document)] + block.givens if block.givens else []
        bodies.append((givens, body))
    source = imports + hoisted_all + file_scope_all
    source += ["static void NFKDocumentationSnippet(void)", "{", f'#line 1 "{CONTEXT}"', context, "{"]
    for givens, body in bodies:
        source += givens + body
    source += ["}", "}"]
    return "\n".join(source) + "\n"


def companion_header(package):
    build = ROOT / package / ".build"
    candidates = list(build.glob(f"**/GeneratedModuleMaps/{package}-Swift.h"))
    candidates += list(build.glob(f"**/{package}.build/include/{package}-Swift.h"))
    return max(candidates, key=lambda path: path.stat().st_mtime) if candidates else None


def resolve_headers(build):
    headers = {}
    for package in COMPANIONS:
        if build:
            result = subprocess.run(["swift", "build", "--target", package], cwd=ROOT / package,
                                    capture_output=True, text=True)
            if result.returncode != 0:
                sys.exit(f"error: `swift build --target {package}` failed:\n{result.stdout}{result.stderr}")
        header = companion_header(package)
        if header is None:
            sys.exit(f"error: no {package}-Swift.h under {package}/.build. Run `cd {package} && swift build`.")
        headers[package] = header
    return headers


def write_module_map(directory, headers):
    umbrella = ROOT / "Sources/InferKit/include/InferKit/InferKit.h"
    entries = [f'module InferKit {{ umbrella header "{umbrella}" export * }}']
    entries += [f'module {name} {{ header "{header}" export * }}' for name, header in headers.items()]
    path = directory / "module.modulemap"
    path.write_text("\n".join(entries) + "\n")
    return path


def compile_unit(source_path, module_map, module_cache, sdk):
    command = [
        "xcrun", "clang", "-fsyntax-only", "-fobjc-arc", "-fmodules",
        f"-fmodules-cache-path={module_cache}", f"-fmodule-map-file={module_map}",
        "-isysroot", sdk, "-target", DEPLOYMENT_TARGET,
        f"-I{ROOT / 'Sources/InferKit/include'}", "-Wall", "-Werror", "-ferror-limit=0",
        "-fno-caret-diagnostics", "-fno-color-diagnostics",
    ] + SUPPRESSED_WARNINGS + [str(source_path)]
    result = subprocess.run(command, capture_output=True, text=True)
    return result.returncode, result.stderr


def relative_diagnostics(text):
    lines = []
    for line in text.splitlines():
        line = line.replace(str(ROOT) + "/", "")
        if re.match(r"^\d+ errors? generated\.$", line):
            continue
        lines.append(line)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("documents", nargs="*", default=DEFAULT_DOCUMENTS)
    parser.add_argument("--no-build", dest="build", action="store_false",
                        help="use the companion headers already in .build without building")
    parser.add_argument("--keep", metavar="DIR", help="write the generated sources to DIR and keep them")
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    arguments = parser.parse_args()

    headers = resolve_headers(arguments.build)
    sdk = subprocess.check_output(["xcrun", "--show-sdk-path"], text=True).strip()
    context = CONTEXT.read_text()
    module_cache = ROOT / ".build/objc-snippet-check/ModuleCache"
    module_cache.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="objc-snippets-") as scratch:
        work = Path(arguments.keep or scratch)
        work.mkdir(parents=True, exist_ok=True)
        return check(arguments, headers, sdk, context, module_cache, work)


def check(arguments, headers, sdk, context, module_cache, work):
    module_map = write_module_map(work, headers)

    units, skipped = [], []
    for document in arguments.documents:
        chain = []
        for block in read_blocks(document):
            if block.skip_reason:
                skipped.append(block)
                chain = []
                continue
            chain = chain + [block] if block.continues and chain else [block]
            source_path = work / f"snippet-{len(units):03d}.m"
            source_path.write_text(translation_unit(chain, context))
            units.append((block, source_path))

    # The first compile builds the module cache that the rest share.
    first = compile_unit(units[0][1], module_map, module_cache, sdk) if units else None
    with concurrent.futures.ThreadPoolExecutor(max_workers=arguments.jobs) as pool:
        rest = list(pool.map(lambda unit: compile_unit(unit[1], module_map, module_cache, sdk), units[1:]))
    results = ([first] if first else []) + rest

    failures = 0
    for (block, source_path), (status, diagnostics) in zip(units, results):
        if status != 0:
            failures += 1
            print(f"--- {block.location} ({source_path.name})")
            print(relative_diagnostics(diagnostics))
    for block in skipped:
        print(f"skipped {block.location}: {block.skip_reason}")
    print(f"{len(units)} Objective-C blocks checked, {failures} failed, {len(skipped)} skipped.")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
